#!/bin/bash
curl -d '{"username": "u", "password": "p", "correlationId": "123" , "captureOrder": ["pan", "expiryDate", "cvv"]}' --header "SECRET: secret"  -H "Accept: application/json" -H "Content-Type: application/json" -X POST http://192.168.56.8:8080/startCapture
